#include "test_support.hpp"

#include <vector>

int main() {
  vesper_test::Context ctx;
  const std::vector<vesper_test::ScriptCase> cases{
      {"advanced-01", vesper::Status::ok,
       "VSP1\nDOC 1 a 00\nDIGEST doc 1\nVERIFY 1\n"},
      {"advanced-02", vesper::Status::ok,
       "VSP1\nPAGE 1 aabbccdd\nDIGEST page 1\nVERIFY 2\n"},
      {"advanced-03", vesper::Status::ok,
       "VSP1\nDOC 2 b 0102\nPAGE 2 1122\nMERGE mixed\nNEXT 2\n"},
      {"advanced-04", vesper::Status::ok,
       "VSP1\nDOC 3 c 03\nISSUE reader 4\nCHECKTICKET 0\n"},
      {"advanced-05", vesper::Status::ok,
       "VSP1\nDOC 4 d 04\nISSUE writer 5\nRENEWTICKET 0 3\nCHECKTICKET 0\n"},
      {"advanced-06", vesper::Status::ok,
       "VSP1\nDOC 5 e 05\nPAGE 3 334455\nNODE 1 8\nSAMPLE all 6\nFOLD\n"},
      {"advanced-07", vesper::Status::ok,
       "VSP1\nDOC 6 f 06\nSNAPSHOT 1\nDOC 7 g 07\nSNAPSHOT 2\nDIFFSNAP 1 2\n"},
      {"advanced-08", vesper::Status::ok,
       "VSP1\nDOC 8 h 08\nDIGEST doc 8\nMERGE docs\nNEXT 1\nISSUE audit 2\n"},
      {"advanced-09", vesper::Status::ok,
       "VSP1\nPAGE 4 a1a2a3a4\nDIGEST page 4\nMERGE pages\nNEXT 1\n"},
      {"advanced-10", vesper::Status::ok,
       "VSP1\nLINKS 2 4 8\nDIGEST links 0\nMERGE links\nNEXT 2\n"},
      {"advanced-11", vesper::Status::ok,
       "VSP1\nNODE 2 16\nWATCH 2\nDIGEST nodes 0\nSAMPLE nodes 2\nFOLD\n"},
      {"advanced-12", vesper::Status::ok,
       "VSP1\nDOC 9 i 09\nDIGEST events 0\nVERIFY 3\n"},
      {"advanced-13", vesper::Status::ok,
       "VSP1\nDOC 10 j 0a\nPAGE 5 0f0e0d0c\nMERGE mixed\nNEXT 1\nNEXT 1\n"},
      {"advanced-14", vesper::Status::ok,
       "VSP1\nDOC 11 k 0b\nISSUE alpha 8\nRENEWTICKET 0 8\nCHECKTICKET 0\n"},
      {"advanced-15", vesper::Status::ok,
       "VSP1\nDOC 12 l 0c\nPAGE 6 01020304\nSAMPLE all 4\nFOLD\n"},
      {"advanced-16", vesper::Status::ok,
       "VSP1\nDOC 13 m 0d\nSNAPSHOT 3\nPAGE 7 55667788\nSNAPSHOT 4\nDIFFSNAP 3 4\n"},
      {"advanced-17", vesper::Status::ok,
       "VSP1\nDOC 14 n 0e\nDIGEST doc 14\nVERIFY 9\nISSUE beta 3\n"},
      {"advanced-18", vesper::Status::ok,
       "VSP1\nPAGE 8 deadbeef\nMERGE pages\nNEXT 1\nSAMPLE pages 1\nFOLD\n"},
      {"advanced-19", vesper::Status::ok,
       "VSP1\nDOC 15 o 0f\nSNAPSHOT 5\nDOC 16 p 10\nSNAPSHOT 6\nDIFFSNAP 5 6\nDIGEST events 0\n"},
      {"advanced-20", vesper::Status::ok,
       "VSP1\nDOC 17 q 11\nPAGE 9 01010101\nMERGE mixed\nNEXT 2\nSAMPLE all 8\nFOLD\n"},
      {"advanced-21", vesper::Status::invalid_state,
       "VSP1\nVERIFY 1\n"},
      {"advanced-22", vesper::Status::invalid_state,
       "VSP1\nNEXT 1\n"},
      {"advanced-23", vesper::Status::limit,
       "VSP1\nISSUE BAD 4\n"},
      {"advanced-24", vesper::Status::limit,
       "VSP1\nCHECKTICKET 4\n"},
      {"advanced-25", vesper::Status::unsupported,
       "VSP1\nSAMPLE weird 1\n"},
      {"advanced-26", vesper::Status::invalid_state,
       "VSP1\nFOLD\n"},
      {"advanced-27", vesper::Status::not_found,
       "VSP1\nDIFFSNAP 1 2\n"},
      {"advanced-28", vesper::Status::unsupported,
       "VSP1\nMERGE odd\n"},
      {"advanced-29", vesper::Status::limit,
       "VSP1\nSAMPLE docs 0\n"},
      {"advanced-30", vesper::Status::limit,
       "VSP1\nNEXT 0\n"}};

  vesper_test::run_cases(ctx, cases);
  return vesper_test::finish(ctx);
}
