#include "test_support.hpp"

#include <vector>

int main() {
  vesper_test::Context ctx;
  const std::vector<vesper_test::ScriptCase> cases{
      {"session-01", vesper::Status::ok,
       "VSP1\nSIGPLAN 1 1\nFINALIZE\nSIGN\n"},
      {"session-02", vesper::Status::ok,
       "VSP1\nROLE analyst\nGRANT analyst read\nCHECK analyst read\n"},
      {"session-03", vesper::Status::ok,
       "VSP1\nROLE writer\nGRANT writer read\nGRANT writer write\nCHECK writer write\n"},
      {"session-04", vesper::Status::ok,
       "VSP1\nTIME 1 100\nWINDOW 50 150\nRETAIN 1\n"},
      {"session-05", vesper::Status::ok,
       "VSP1\nTIME 1 100\nTIME 2 200\nWINDOW 50 250\nRETAIN 2\n"},
      {"session-06", vesper::Status::ok,
       "VSP1\nROLE reader\nGRANT reader read\nCHECK reader write\nSIGPLAN 2 2\nFINALIZE\nSIGN\n"},
      {"session-07", vesper::Status::ok,
       "VSP1\nROLE audit\nGRANT audit inspect\nTIME 3 300\nWINDOW 250 350\n"},
      {"session-08", vesper::Status::ok,
       "VSP1\nTIME 5 500\nTIME 6 600\nRETAIN 1\n"},
      {"session-09", vesper::Status::ok,
       "VSP1\nROLE operator\nGRANT operator read\nGRANT operator write\nCHECK operator execute\n"},
      {"session-10", vesper::Status::ok,
       "VSP1\nSIGPLAN 3 3\nFINALIZE\nSIGN\nROLE signer\nGRANT signer approve\nCHECK signer approve\n"},
      {"session-11", vesper::Status::ok,
       "VSP1\nTIME 7 700\nWINDOW 650 750\nRETAIN 1\nSIGPLAN 1 1\nFINALIZE\nSIGN\n"},
      {"session-12", vesper::Status::ok,
       "VSP1\nROLE guard\nGRANT guard read\nGRANT guard inspect\nCHECK guard inspect\n"},
      {"session-13", vesper::Status::ok,
       "VSP1\nTIME 8 800\nTIME 9 900\nWINDOW 800 900\n"},
      {"session-14", vesper::Status::ok,
       "VSP1\nROLE alpha\nGRANT alpha read\nROLE beta\nGRANT beta write\nCHECK alpha read\nCHECK beta write\n"},
      {"session-15", vesper::Status::ok,
       "VSP1\nSIGPLAN 4 4\nFINALIZE\nSIGN\nTIME 10 1000\nWINDOW 900 1100\n"},
      {"session-16", vesper::Status::ok,
       "VSP1\nROLE gamma\nGRANT gamma export\nCHECK gamma export\n"},
      {"session-17", vesper::Status::ok,
       "VSP1\nTIME 11 1100\nTIME 12 1200\nTIME 13 1300\nWINDOW 1150 1350\nRETAIN 2\n"},
      {"session-18", vesper::Status::ok,
       "VSP1\nROLE delta\nGRANT delta review\nCHECK delta review\nSIGPLAN 2 2\nFINALIZE\nSIGN\n"},
      {"session-19", vesper::Status::ok,
       "VSP1\nROLE epsilon\nGRANT epsilon read\nCHECK epsilon missing\n"},
      {"session-20", vesper::Status::ok,
       "VSP1\nTIME 14 1400\nRETAIN 1\n"},
      {"session-21", vesper::Status::limit,
       "VSP1\nSIGPLAN 0 1\n"},
      {"session-22", vesper::Status::limit,
       "VSP1\nROLE BAD\n"},
      {"session-23", vesper::Status::not_found,
       "VSP1\nGRANT nobody read\n"},
      {"session-24", vesper::Status::not_found,
       "VSP1\nCHECK nobody read\n"},
      {"session-25", vesper::Status::limit,
       "VSP1\nTIME 0 10\n"},
      {"session-26", vesper::Status::malformed,
       "VSP1\nWINDOW 20 10\n"},
      {"session-27", vesper::Status::limit,
       "VSP1\nRETAIN 0\n"},
      {"session-28", vesper::Status::invalid_state,
       "VSP1\nSIGN\n"},
      {"session-29", vesper::Status::invalid_state,
       "VSP1\nFINALIZE\n"},
      {"session-30", vesper::Status::invalid_state,
       "VSP1\nROLE ok\nGRANT ok read\nGRANT ok read\n"}};

  vesper_test::run_cases(ctx, cases, vesper::Profile::all);
  return vesper_test::finish(ctx);
}
